name: build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # This enables the ability to execute Arm binaries for us.
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - run: ./build.sh
